### ISSUE TITLE
Version 0.0.10 does not work with JupyterLab

### ISSUE THREAD

**Issue by vilim** [matplotlib/jupyter-matplotlib#29]
Hello,

Thank you for developing this module! I was able to use it last week with Jupyter Lab (the newest release, 0.28.12), but now I updated to the version 0.0.10 and the widget does not display anymore
The message is 
`Error displaying widget`

And in the chrome Javascript console the following appears:
`Module jupyter-matplotlib, semver range ^0.2.1 is not registered as a widget module`

I tried downgrading to v0.08  which used to work, but does not anymore.
The normal ipywidgets still work.

**Comment by thomasaarholt** [comment]
I am experiencing the same. I suspect it may have something to do with
having upgraded jupyter, although I don’t really know.

**Comment by blink1073** [comment]
Thanks for the report!  Fixed in 0.0.11.

**Comment by vilim** [comment]
I upgraded to 0.0.11, uninstalled ipywidgets, run jupyter clean, installed both ipywidgets and ipympl again but the issue persists.

**Comment by blink1073** [comment]
I missed a step in the release process, can you please try 0.0.12?

**Comment by vilim** [comment]
It does work now. Thank you for the quick responses!

**Comment by blink1073** [comment]
Cheers!
